<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
  </PropertyGroup>
  <ItemGroup>
    <FrameworkReference Include="Microsoft.AspNetCore.App" />
    <PackageReference Include="Anthropic" Version="12.29.1" />
    <PackageReference Include="Microsoft.AspNetCore.Identity.EntityFrameworkCore" Version="8.*" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.SqlServer" Version="8.*" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.Design" Version="8.*">
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
      <PrivateAssets>all</PrivateAssets>
    </PackageReference>
    <PackageReference Include="Stripe.net" Version="46.*" />
    <PackageReference Include="MailKit" Version="4.*" />
    <PackageReference Include="WebPush" Version="1.0.12" />
  </ItemGroup>
  <ItemGroup>
    <ProjectReference Include="..\Domain.HomePlanner\Domain.HomePlanner.csproj" />
    <ProjectReference Include="..\Application.HomePlanner\Application.HomePlanner.csproj" />
    <ProjectReference Include="..\Framework.HomePlanner\Framework.HomePlanner.csproj" />
  </ItemGroup>
</Project>
